name: gutenberg
description: Gutenberg Free Books App.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  equatable: ^2.0.5
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  json_serializable: ^6.7.1
  mockito: ^5.4.2

flutter:
  uses-material-design: true
  assets:
    - assets/

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/generated\/*