name: gutenberg
description: Gutenberg Free Books App.

publish_to: 'none'

version: 0.0.1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2
  dio: ^5.3.2
  environment_config: ^3.1.0
  equatable: ^2.0.5
  feather_icons: ^1.2.0
  flutter_bloc: ^8.1.3
  get_it: ^7.6.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  marquee: ^2.2.3
  provider: ^6.0.5
  retrofit: ^4.0.1
  shimmer: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  bloc_test: ^9.1.4
  build_runner: ^2.4.6
  flutter_lints: ^2.0.0
  import_sorter: ^4.6.0
  infinite_scroll_pagination: ^4.0.0
  intl_translation: ^0.18.2
  json_serializable: ^6.7.1
  mockito: ^5.4.2
  retrofit_generator: ^7.0.8

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 700

import_sorter:
  comments: false
  ignored_files:
    - \/lib\/generated\/*